### ISSUE TITLE
Rezerwacja wizyt przez rejestratorkę

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#11]
Gdy rejestratorka rezerwuję wizytę dla pacjenta X to mail potwierdzający rezerwację wizyty przychodzi do rejestratorki zamiast do pacjenta . Oczywiście na wizytę zapisany jest prawidłowo  pacjent .

**Comment by kopsow** [comment]
Do weryfikacji

**Comment by garbaty82** [comment]
działa!
