### ISSUE TITLE
Rejestracja - nowe konto - Pacjent

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#12]
Na maila nie przychodzą linki aktywacyjne nowego konta pacjenta

**Comment by garbaty82** [comment]
Test robiła Pani Bakony i mała wtopa :) . Ale w tym czasie się DNS wywalił więc zgoniłem że może to być spowodowane właśnie tym i łykła.

**Comment by garbaty82** [comment]
Przychodzi link aktywacyjny ale nie działa.

**Comment by kopsow** [comment]
Tzn?
Pojawia się jakiś błąd? Jeśli tak to jaki

**Comment by garbaty82** [comment]
w pasku strony wyświetla się  "http://www-super-med.pl/auth/active/admin@netmed.pl"
a następnie : 
Ta witryna jest nieosiągalna

**Comment by kopsow** [comment]
Myślnik zamiast kropki. Teraz linki aktywacyjne powinny mieć już poprawny format.

**Comment by garbaty82** [comment]
Działa :)
