### ISSUE TITLE
Administrator -> edycja użytkowników

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#14]
Przy edytowaniu konta pacjent nie ma możliwości zmiany numeru pesel . To samo dotyczy lekarza -> nie ma możliwości poprawy NPWZ. 
Nie działa też możliwość zmiany jakichkolwiek danych po zatwierdzeniu , wywala błąd.

**Comment by kopsow** [comment]
To również poprawione, do weryfikacji

**Comment by garbaty82** [comment]
Działa super ale bez walidacji. Ale to jest chyba w innym wątku.
