### ISSUE TITLE
Specjalizacja i krótki opis lekarza + foto 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#15]
Wojtku czy można dodać w tej funkcjonalności żeby można było edytować foto lekarza + specjalizacja i krótki opis danego lekarza. 
Przy rejestracji do lekarza "Wybierz swojego lekarza" .

**Comment by garbaty82** [comment]
Duży będzie z tym problem ?

**Comment by kopsow** [comment]
Duży, zmiana bazy, zmiany w kontrolerze i w modelu

**Comment by garbaty82** [comment]
To może jakaś inna forma prezentacji lekarzy  bez bajerów . ?

**Comment by kopsow** [comment]
Czyli taka jaka jest  :)

23.02.2017 23:57 "garbaty82" <notifications@github.com> napisał(a):

**Comment by garbaty82** [comment]
yyy chyba nie . Jakieś "Pellentesque pharetra ex et risus rutrum faucibus. Sed magna leo, molestie ut laoreet eget, dictum at purus. Nulla a feugiat ex." - to nie potrzebne

**Comment by kopsow** [comment]
To jest lorem ipsum standard przy wypełnianiu kolumn tekstem:)
Googlnij sobie i jej to jutro sprzedaj jako ciekawostkę  ;)

24.02.2017 00:00 "garbaty82" <notifications@github.com> napisał(a):

**Comment by garbaty82** [comment]
spoko J korzenie 45 pne ;)

**Comment by kopsow** [comment]
Kurwa, nie ludzkie godziny pracy :)
Dodałem ale tak na szybko, żeby pokazać funkcjonalność nie mam już siły na ładne nazwy

Administrator ma nową pozycję w meni "AVATAR LEKARZA"
Tam może ustawiać zdjęcie, specjalizację i opis. Ja wiem, że to powinno być razem z edycją pacjenta ale nie ma czasu.
Poddawałem przykładowe fotki i opisy.

Co z tym nie działa ok?
- za każdym razem nadpisujesz dane
- nie można edytować
i pewnie coś jeszcze ale już nie myślę

**Comment by garbaty82** [comment]
zajebista robota . Funkcjonalności edycji nie będę pokazywał bo już raczej nic dzisiaj nie zrobisz. Sprawdzę resztę czy chodzi płynnie i zobaczymy jaka będzie jej decyzja .

**Comment by garbaty82** [comment]
Wracając do tematu . Wojtku jak mi ma sypać błędami to wole jakoś inaczej pokazać wybór tych lekarzy (chodź to jest zajebiste a zwłaszcza pudzian :) - kurwa okulista HAHA ) . 
Lekarz przy edycji własnych danych sypie błędami ale to pewnie związane z tym samym co powyżej.

**Comment by kopsow** [comment]
poprawione

**Comment by garbaty82** [comment]
jest ok !
