### ISSUE TITLE
Pesel - nowe konto pacjenta

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#18]
walidacja na pesel. Doczepiła się.

**Comment by kopsow** [comment]
W sensie, że nie jest sprawdzane czy jest poprawny numer PESEL ?
W sensie suma kontrolna itd. ?

**Comment by garbaty82** [comment]
tak

**Comment by kopsow** [comment]
Dodałem pełną walidację numeru PESEL

**Comment by garbaty82** [comment]
doskonale
