### ISSUE TITLE
Administrator - opcja usuwanie 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#20]
Usuń możliwość usuwania użytkowników . Tylko blokowanie i aktywacja :)

**Comment by garbaty82** [comment]
Może to zostaw na sam koniec bo dobrze było by żeby przed oddaniem baza była  w miarę czysta a pacjenci żeby nie byli powiązani z żadnymi wizytami :)

**Comment by kopsow** [comment]
Usunąłem tą opcję

**Comment by garbaty82** [comment]
nie teraz ! trzeba to wszystko poczyścić . maili mi branie do testów :)

**Comment by kopsow** [comment]
To czyść przez phpmyadmin :)

**Comment by garbaty82** [comment]
nom ok :)
