### ISSUE TITLE
Rezerwacja wizyty - Pacjent - po terminie

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#24]
Pacjent widzi dni z szablonu lekarza do rejestracji z przeszłości. 
Nie powinien mieć (widzieć) terminów rejestracji z datą wsteczną.

**Comment by kopsow** [comment]
Zrobione. Obecnie pacjent może wybierać z terminów z dnia obecnego lub z przyszłości.

**Comment by garbaty82** [comment]
super!

**Comment by garbaty82** [comment]
pacjent może zarejestrować się na większą ilość wizyt :(

**Comment by kopsow** [comment]
Poprawione. Naprawa poprzedniego błędy pociągnęła za sobą ten.
Teraz już powinno być ok.

**Comment by garbaty82** [comment]
działa :)
