### ISSUE TITLE
Odwoływanie wizyt - Administrator - na koniec

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#25]
Administrator powinien mieć funkcje odwoływania wizyt .

**Comment by kopsow** [comment]
Zrobione, do weryfkacji

**Comment by garbaty82** [comment]
Wywala błąd: 
/var/www/supermed/vendor/zendframework/zendframework/library/Zend/Mail/Message.php:513

**Comment by kopsow** [comment]
Dla jakiej wizyty?

**Comment by kopsow** [comment]
Domyślam się w czym problem. To kwestia funkcjonalności.
Domyślnie odwołanie wizyty powinno skutkować mailem do pacjenta. Ale teraz można zakładać konta pacjentów bez maila.
Sprawdź na pacjencie, który ma konto pocztowe ustawione.

**Comment by garbaty82** [comment]
Tak jak piszesz.

**Comment by garbaty82** [comment]
ten kto nie ma maila wywala błąd

**Comment by kopsow** [comment]
Poprawiłem, do weryfikacji

**Comment by garbaty82** [comment]
ok super działa.
