### ISSUE TITLE
Edycja danych - lekarz -pacjent 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#28]
Otwieram nowy wątek dotyczący  lekarza i pacjenta . Przy próbie edycji swoich danych  - przy pierwszej zmianie i zatwierdzeniu wszystko jest ok ale jak chcemy zmienić znowu to odznacza nam się automatycznie opcja "zweryfikuj" co skutkuję dezaktywacją konta.

**Comment by kopsow** [comment]
Poprawione

**Comment by garbaty82** [comment]
to ok tylko przy zmianie hasła na inne czyści się pole mail :( . Nowy wątek ?

**Comment by garbaty82** [comment]
przy zmianie loginu to nie występuje ten problem

**Comment by kopsow** [comment]
Poczekaj sprawdzę

**Comment by kopsow** [comment]
Sprawdź teraz

**Comment by garbaty82** [comment]
Dzięki. Działa ! :)
