### ISSUE TITLE
Rejestracja - funkcjonalność 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#29]
Przy wyborze pacjenta na wizytę mamy podane tylko imię i nazwisko . Czy jest opcja żeby przy tym była również data urodzenia. Mogą być pacjenci o tym samym imieniu i nazwisku .

**Comment by kopsow** [comment]
Rejestratorka  w liście pacjentów obok imienia nazwiska ma teraz datę urodzenia

**Comment by garbaty82** [comment]
Zajebiście ! :)
