### ISSUE TITLE
Dodawanie użytkownika - walidacja mail

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#30]
Przy dodawaniu użytkownika przez rejestrację czy też administratora  nie powinno być wymagane uzupełnienie pola " adres email" . Nie każdy pacjent ma maila. Przy indywidualnej rejestracji pacjenta wymagane jest uzupełnienie maila.

**Comment by kopsow** [comment]
Zrobione

**Comment by garbaty82** [comment]
super!
