### ISSUE TITLE
Status wizyty 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#31]
Lekarz mógłby mieć opcje odznaczenia w jakiejś formie że wizyta została zrealizowana . 
Tylko info że wizyta się odbyła - guzik "zrealizuj" i zmiana statusu na "zrealizowana" . To tez musiałaby widzieć u siebie rejestratorka . 
Rejestratorka ma tylko widzieć status "zrealizowana" .
Admin też powinien widzieć tylko status "zrealizowana ".

**Comment by kopsow** [comment]
Zamiast statusów (dodatkowa tabela) proponuję realizację za pomocą kolorów.
Zobacz sobie np.
login jkoperski
pass: kopsow

**Comment by garbaty82** [comment]
nie działa hasło jkoperski

**Comment by kopsow** [comment]
kopsow82 ;)

**Comment by garbaty82** [comment]
sprawdziłem na innym lekarzu . super. Robić testy ?

**Comment by kopsow** [comment]
Działaj

**Comment by garbaty82** [comment]
nom działa
