### ISSUE TITLE
Konto pacjent - zmiana pesel

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#32]
Pacjent nie powinien móc zmienić swojego nr pesel .

**Comment by kopsow** [comment]
A który może?
Bo loguję się na konto pacjenta i nie widzę, możliwości zmiany numeru pesel:
![image](https://cloud.githubusercontent.com/assets/25557253/23257652/12c8f5e6-f9c5-11e6-9a69-5e105fba000c.png)

**Comment by garbaty82** [comment]
Przepraszam chyba namieszałem . Masz rację. Pacjent nie powinien  zmienić swojego loginu bo wywala błąd jak się zdubluje  i najlepiej jakby nie mógł też mieszać w swojej dacie urodzenia.

**Comment by kopsow** [comment]
Poprawione.
Pacjent może tylko zmieniać imię, nazwisko, hasło, numer telefonu.
Do weryfikacji

**Comment by garbaty82** [comment]
Dajesz wyślij i wywala:
/var/www/supermed/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Pdo/Statement.php:244

**Comment by garbaty82** [comment]
puste lub zmienione dane które pacjent może zmienić przy kliknięciu wyślij błąd jak wyżej

**Comment by kopsow** [comment]
Nie widzę tego.
Na jakim koncie się logujesz, jakie dane zmieniasz lub edytujesz

**Comment by garbaty82** [comment]
konto panek
hasło: 12345

**Comment by kopsow** [comment]
Znalazłem problem.
Sprawdź teraz.

**Comment by garbaty82** [comment]
super! działa!
