### ISSUE TITLE
Adminsitrator -edycja danych pacenta

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#33]
U pacjenta który ma nieaktywne konto wywala błąd klikając na "Edytuj" 
/var/www/supermed/module/Application/src/Application/Model/PatientTable.php:44

**Comment by kopsow** [comment]
Ale edycja z poziomu jakiego użytkownika ?

**Comment by kopsow** [comment]
Nie potrafię uzyskać tego błędu ani na koncie administratora ani rejestracji. Więcej szczegółów proszę.

**Comment by garbaty82** [comment]
Ok już wiem w czym problem :) . Widzę że usunąłeś już tego użytkownika. 
Nie chciałem Ci o tym pisać bo wydaje mi się to na chwile obecną zbędne ale przy tworzeniu nowego pacjenta po uzupełnieniu podstawowych danych które wymaga system a następnie przejściu do opcji uzupełniania numeru pesel (nie uzupełniam nr  pesel ) i daje wstecz na stronie www -> wywala błąd ale użytkownik się tworzy . I chyba sprawdzałem to na tym użytkowniku

**Comment by garbaty82** [comment]
coś z tym robisz czy olewamy ? Ja bym to zostawił ewentualnie na sam koniec. Tak czy inaczej przy tworzeniu użytkownika personel który to robi powinien mieć opcję wstecz ...

**Comment by kopsow** [comment]
No tak, wywaliłem go bo widziałem że jest w tabeli użytkownicy, ale brak go w tabeli pacjenci.
Założyłem, że wysypała się przeglądarka albo nie było netu w trakcie tworzenie konta i stąd ten błąd :)

A po co personelowi opcja wstecz ?

**Comment by garbaty82** [comment]
Masz racje. Idziemy do przodu a nie cofamy się !
