### ISSUE TITLE
Potwierdzenie odwołania wizyty na maila

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#34]
nie działa

**Comment by kopsow** [comment]
Więcej info

**Comment by garbaty82** [comment]
Odwołuje wizytę czy to z konta admina czy rejestratorki i nie ma info na mailu o odwołanej wizycie "Anulowanie wizyty" .

**Comment by kopsow** [comment]
Teraz powinno być ok. Do sprawdzenia

**Comment by garbaty82** [comment]
Super przychodzą na maila ale fizycznie nie znikają tylko dalej widnieją w przeglądzie "Zaplanowane wizyty"

**Comment by garbaty82** [comment]
nie znikają wizyty

**Comment by kopsow** [comment]
Teraz będą już znikać. Do sprawdzenia

**Comment by garbaty82** [comment]
działa :)
