### ISSUE TITLE
Logowanie pacjent

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#35]
zaloguj się na pacjenta login: panek
hasło: 123456
i kliknij "moje wizyty" lub "rezerwuj wizytę" 

Błąd: 
/var/www/supermed/vendor/zendframework/zendframework/library/Zend/Db/Adapter/Driver/Mysqli/Statement.php:208

**Comment by kopsow** [comment]
sprawdzam

**Comment by kopsow** [comment]
Tak to się kończy jak się zmienia strukturę bazę w trakcie :)
Zrobione, do weryfikacji

**Comment by garbaty82** [comment]
Rozumiem. Wojtku nie wprowadzany już żadnych funkcjonalności więc myślę że będzie z górki :). Już sprawdzam

**Comment by garbaty82** [comment]
pacjent może zarejestrować się na większą ilość wizyt :(

**Comment by kopsow** [comment]
Nie ten wątek ;)

**Comment by garbaty82** [comment]
ok otwieram ponownie zgodnie z tematyką
