### ISSUE TITLE
Zapisz pacjenta z konta rejestratorki

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#36]
Proszę zmień w "Zapisz pacjenta" -> wybór pacjenta -> wybierz pacienta na wybierz pacjenta (literówka i->j)  .

Druga sprawa . Jeżeli nie wybierzemy pacjenta lub lekarza i damy sprawdź termin to wywala błąd. 
Może jakaś walidacja "Wybierz pacjenta" "Wybierz lekarza" .

**Comment by kopsow** [comment]
Poprawiłem obie rzeczy do weryfikacji

**Comment by garbaty82** [comment]
działa
