### ISSUE TITLE
Rejestratorka - dodawanie pacjenta

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#38]
po przejściu do zakładki gdzie uzupełnia się PESEL i resztę danych po kliknięciu zapisz , nic się nie dzieje. Wygląda na to że pacjent dodawany jest do bazy. Bo drugim kliknięciu "Zapisz" wywala błąd.

**Comment by kopsow** [comment]
Teraz zobacz

**Comment by garbaty82** [comment]
jest ok super ale..... to samo co w wątku z data urodzenia . Musi być tu tez obowiązek uzupełnienia. 
Nowy wątek otwierać ?

**Comment by kopsow** [comment]
Zobacz teraz

**Comment by garbaty82** [comment]
ale po co . Jak zrobiłeś walidację to już problem nie będzie sie pojawiał

**Comment by kopsow** [comment]
Ale sprawdzić zawsze warto ;)

**Comment by garbaty82** [comment]
sory nie ten wątek

**Comment by garbaty82** [comment]
![image](https://cloud.githubusercontent.com/assets/25869688/23281023/d836d37e-fa1b-11e6-9a1d-2f8c79b62b17.png)

The input does not appear to be a valid date - nie potrzebne to

**Comment by kopsow** [comment]
Dobra nie mogą tego całkiem wywalić, coś zend się uparł na ta opcję.
Zmieniłem treść komunikatu po naszemu :)
