### ISSUE TITLE
Nie widać pacjenta przy zapisywaniu  - nowe konto

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#40]
Założyłem nowe konto pacjenta   przez zarejestruj . Przyszedł link aktywacyjny itd. 
Pacjent jest aktywny ale przy zalogowaniu np na konto rejestratorki nie widać pacjenta w "wybór pacjenta" . 
Jest puste pola (widmo)

**Comment by kopsow** [comment]
W tej chwili edytuję ten kontroler, może to stąd wynika błąd.

**Comment by garbaty82** [comment]
nie już wiem

**Comment by garbaty82** [comment]
pacjent nie miał uzupełnionej daty urodzenia

**Comment by garbaty82** [comment]
raz jeszcze na nowo utworze konto pacjenta z poziomu zarejestruj . Jestem pewny że uzupełniałem datę urodzenia

**Comment by garbaty82** [comment]
można założyć konto pacjenta bez podawania daty urodzenia. Musi być walidacja na to

**Comment by kopsow** [comment]
Pewnie, że można nigdzie nie było wcześniej powiedziane, że nie można :)

**Comment by garbaty82** [comment]
hihi :) tylko szkoda że go nie widać przy zapisywaniu na wizytę z poziomu rejestratorki i lekarza

**Comment by kopsow** [comment]
Dodałem walidację na datę urodzenia.
Czego nie widać ?

**Comment by garbaty82** [comment]
jak nie jest uzupełniona data urodzenia to widać puste pole przy wyborze pacjenta do zarejestrowania na wizytę z poziomu lekarza lub rejestratorki

**Comment by kopsow** [comment]
Zrób i wklej mi tu screena

**Comment by garbaty82** [comment]
ale po co . Jak zrobiłeś walidację to już problem nie będzie sie pojawiał

**Comment by kopsow** [comment]
Ale właśnie chodzi o to, że ja widze pacjentów ok + data urodzenia w postacji 0000-00-00
Ciekaw jestem jak to u ciebie wygląda

**Comment by garbaty82** [comment]
jak jest data 00000 to widać. ale jak  nic nie wpiszesz w date urodzenia to wtedy jest widmo. jak jest juz walidacja to jest ok

**Comment by garbaty82** [comment]
nie ma tematu . szkoda czasu

**Comment by kopsow** [comment]
No mam nadzieję :) Bo jutr planuję spać do południa ;)
