### ISSUE TITLE
Pacjent - nowe konto

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#41]
Przy zakładaniu nowego konta przez użytkownika wywala błąd :

Fatal error: Call to a member function format() on a non-object in /var/www/supermed/vendor/zendframework/zendframework/library/Zend/Validator/DateStep.php on line 220

**Comment by garbaty82** [comment]
Bez tego nawet do niej nie idę ;) . Będzie pewnie zakładać konto przy mnie :) . 
Wychodzi na to że walidator nie działa PESEL

**Comment by kopsow** [comment]
Zakładanie nowego konta przez: pacjenta, admina czy rejestrację ?

**Comment by kopsow** [comment]
Dobra sam poszukałem, ale stracony czas ;)
Poprawione

**Comment by garbaty82** [comment]
przez każdego

**Comment by kopsow** [comment]
A teraz ?

**Comment by garbaty82** [comment]
sory nie sprawdziłem jeszcze . zgubiłem się w komentarzach

**Comment by garbaty82** [comment]
zaraz dam znać

**Comment by garbaty82** [comment]
jest ok .
