### ISSUE TITLE
pacjent - konto gmail

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#42]
Czemu jak zakładam konto pacjenta z mailem gmail to nie działa link aktywacyjny . Tylko gmail. 

http://www-super-med.pl/auth/active/eserwisant@gmail.com

pojawia się po www "-" . Na innych kontach nie googlowskich linki działają bez problemu .

**Comment by kopsow** [comment]
U mnie na gmailu działa:
![image](https://cloud.githubusercontent.com/assets/25557253/23311338/0c8f68da-fab6-11e6-83f7-2cba639f6017.png)

**Comment by garbaty82** [comment]
u mnie też działa ;) .
