### ISSUE TITLE
Home - Instrukcja - na głównej stronie 

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#44]
UWAGA!!!

1. W celu rejestracji do lekarza należy założyć konto w systemie www.super-med.pl, podając prawidłowe dane wymagane do utworzenia konta,
prawidłowy i używany adres E-Mail, na który wysyłane są automatycznie wiadomości dla pacjenta,

2. Nie ma możliwości tworzenia kilku kont za pomocą jednego adresu e-mail oraz tego samego numeru PESEL. 

3. Podczas tworzenia konta zostaje wysyłany automatycznie link aktywacyjny w celu weryfikacji użytkownika. Konto należy potwierdzić klikając  w link aktywacyjny. W przypadku nie otrzymania linku prosimy sprawdzić folder SPAM,

4. Jeżeli przy próbie rejestracji do systemu wyskoczy informacja - "Podany PESEL już istnieje!" , proszę udać się do przychodni w celu przeprowadzenia identyfikacji pacjenta na podstawie dokumentu tożsamości.  Ty samym do konta o podanym numerze PESEL zostanie przypisane konto e-mail oraz jednorazowo zostanie nadane hasło . 

4. W razie problemów z działaniem portalu prosimy o kontakt z administratorem portalu super-med.pl poprzez e-mail:
rejestracja@super-med.pl .

**Comment by kopsow** [comment]
dodane

**Comment by garbaty82** [comment]
Wojtku chyba źle napisałem topic . 
Instrukcja ma być po prawej stronie opcji "zarejestruj"  pod "Instrukcja"

**Comment by garbaty82** [comment]
Wojtku jak nie masz siły nic dzisiaj robić to tylko wyprostuj mi ten wątek bo wygląda to na stronie głównej trochę brzydko i idź się w końcu wyśpij :) . Robota zrobiona zajebiście

**Comment by kopsow** [comment]
zrobione

**Comment by garbaty82** [comment]
ok
