### ISSUE TITLE
Zaplanowane wizyty

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#46]
Z konta lekarza , rejestratorki, administrator wchodząc na zakładkę "zaplanowane wizyty" i wybierając filtruj bez uzupełnionych filtrów wywala poniższy błąd: 

Notice: Undefined index: completed in /var/www/supermed/module/Application/view/application/registration/list.phtml on line 41

**Comment by garbaty82** [comment]
Przy sortuj to samo

**Comment by kopsow** [comment]
Poprawione

**Comment by garbaty82** [comment]
got
