### ISSUE TITLE
Zakładanie konta przez Pacjenta

### ISSUE THREAD

**Issue by garbaty82** [kopsow/sm2#47]
Po wypełnieniu danych przez pacjenta przy zakładaniu konta  i kliknięciu wyślij powinna pojawić się informacja że " Na podany adres mail został został wysłany link aktywacyjny".

**Comment by kopsow** [comment]
Zrobione do weryfikacji

**Comment by kopsow** [comment]
Dodałem od razu potwierdzenie aktywacji konta

**Comment by garbaty82** [comment]
super
